---

- name: Install firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld 
    state: started 
    enabled: yes

- name: Allow and limit ssh connection
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 source address="{{ ssh_allow_cidr|default('0.0.0.0/0') }}" port port="22" protocol="tcp" limit value="10/m" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Custom ingress rules
  ansible.posix.firewalld:
    rich_rule: rule family="{{ item.family|default('ipv4') }}" source address="{{ item.src|default('0.0.0.0/0') }}" port port="{{ item.port }}" protocol="{{ item.proto }}" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ firewall_ingress_rules }}"
  when: "{{ firewall_ingress_rules | length > 0 }}"

- name: Disable ssh service, use rich_rule
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: yes
    state: disabled
    immediate: yes