---

- name: enable and start ufw
  ansible.builtin.systemd: 
    name: ufw 
    state: started 
    enabled: yes

- name: Block incoming traffic
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Allow outgoing traffic
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Enabble firewall logging
  community.general.ufw:
    logging: 'on'

- name: Allow and limit ssh connection
  community.general.ufw:
    rule: limit
    direction: in
    proto: tcp
    src: "{{ ssh_allow_cidr|default('0.0.0.0/0') }}"
    port: '22'

- name: Custom ingress rules (port)
  community.general.ufw:
    rule: "{{ firewall_item.rule|default('allow') }}"
    direction: in
    proto: "{{ firewall_item.proto }}"
    src: "{{ firewall_item.src|default('0.0.0.0/0') }}"
    port: "{{ firewall_item.port }}"
  with_items: "{{ firewall_ingress_rules }}"
  loop_control:
    loop_var: firewall_item
  when: 
    - firewall_ingress_rules | length > 0
    - firewall_item.port is defined

- name: Custom ingress rules (open all ports)
  community.general.ufw:
    rule: "{{ firewall_item.rule|default('allow') }}"
    direction: in
    proto: "{{ firewall_item.proto }}"
    src: "{{ firewall_item.src|default('0.0.0.0/0') }}"
  with_items: "{{ firewall_ingress_rules }}"
  loop_control:
    loop_var: firewall_item
  when: 
    - firewall_ingress_rules | length > 0
    - firewall_item.port is not defined

- name: Enable ufw
  community.general.ufw:
    state: enabled