---

- name: Install iptables-legacy
  ansible.builtin.yum:
    name: iptables-legacy
    state: present
  when: ansible_os_family == 'RedHat'

- name: check iptables version
  shell: iptables --version
  register: iptables_version
  ignore_errors: yes

- block:  
    - community.general.alternatives:
        name: iptables
        path: /usr/sbin/iptables-legacy
        link: /usr/sbin/iptables

    - community.general.alternatives:
        name: ip6tables
        path: /usr/sbin/ip6tables-legacy
        link: /usr/sbin/ip6tables

    - ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for iptables-legacy"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
  when: '"nf_tables" in iptables_version.stdout'
  ignore_errors: "{{ ansible_check_mode }}"