---

- setup:

- name: Populate service facts
  ansible.builtin.service_facts:

- include_tasks: 
    file: auth.yml
    apply:
      tags: auth
  tags: auth

- include_tasks: 
    file: authorized-keys.yml
    apply:
      tags: authorized-keys
  tags: authorized-keys

- include_tasks: 
    file: sshd.yml
    apply:
      tags: sshd
  tags: sshd

- include_tasks: 
    file: iptables-legacy.yml
    apply:
      tags: iptables-legacy
  tags: iptables-legacy
  when: 
    - iptables_mode == 'legacy'

- include_tasks: 
    file: "{{ item }}"
    apply:
      tags: firewall
  with_first_found:
    - "firewall-{{ firewall_type[ansible_os_family] }}.yml"
  tags: firewall
  when: 
    - enable_firewall
    - not docker_preserve

- include_tasks: 
    file: firewall-docker.yml
    apply:
      tags: firewall,preserve
  tags: firewall,preserve
  when:
    - enable_firewall
    - docker_preserve

- include_tasks: 
    file: fail2ban.yml
    apply:
      tags: fail2ban
  tags: fail2ban
  when: install_fail2ban